- name: show return valune of command
  hosts: centos
  become: yes
  tasks:
          - name: capture output of id command
            command: uptime
            register: _uptime
          - debug: msg="server is up since {{ _uptime.stdout }}"
